apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevSecops-deployment
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: shark
        image: docker6767/DevSecOpsproduct
        ports:
        - containerPort: 8080
